# Generated by Django 5.0 on 2023-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=130)),
                ('number', models.CharField(help_text='Phone Numbers will be saved without 0 at start like 914838781', max_length=11)),
                ('code_melli', models.TextField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date number saved')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date number saved')),
            ],
        ),
    ]
